### ISSUE TITLE
Error installing meshblu-johnny-five-rpi

### ISSUE THREAD

**Issue by moodybass** [octoblu/meshblu-johnny-five-rpi#1]
Hi there, attempting to install meshblu-johnny-five-rpi. I get the following NPM error when running from the meshbluu-johnny-five-rpi directory. Running Raspberry PI "Wheezy" with Node 0.12.6 and NPM 3.3.10

I've checked the node_modules folder and /raspi-gpio/ does not exist.

Any ideas?

```
npm install

> raspi-gpio@1.4.0 install /home/pi/meshblu-johnny-five-rpi/node_modules/raspi-gpio
> node-gyp rebuild

make: Entering directory '/home/pi/meshblu-johnny-five-rpi/node_modules/raspi-gpio/build'
  CXX(target) Release/obj.target/addon/src/addon.o
  CXX(target) Release/obj.target/addon/src/init.o
../src/init.cc:27:22: fatal error: wiringPi.h: No such file or directory
compilation terminated.
addon.target.mk:90: recipe for target 'Release/obj.target/addon/src/init.o' failed
make: *** [Release/obj.target/addon/src/init.o] Error 1
make: Leaving directory '/home/pi/meshblu-johnny-five-rpi/node_modules/raspi-gpio/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.7-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/meshblu-johnny-five-rpi/node_modules/raspi-gpio
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON meshblu-johnny-five-rpi@1.0.0 No repository field.
npm ERR! Linux 4.1.7-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! raspi-gpio@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raspi-gpio@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the raspi-gpio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raspi-gpio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/meshblu-johnny-five-rpi/npm-debug.log
```

**Comment by moodybass** [comment]
OK - think I've found it.  raspi-gpio is part of raspi.js, the following note applies:

First, be sure that you have installed Raspi.js.

Install with NPM:
npm install raspi-gpio
Warning: this module requires GCC 4.8 or newer. This means that you should be running Raspbian Jesse or newer, released in September of 2015.

I'll get upgrading.  I'll leave this issue open until confirmed working.

**Comment by moodybass** [comment]
Upgraded to Debian Jessie on Raspberry Pi - followed installation instructions.  meshblu-johnny-five-rpi appears to install correctly.

On running node index.js 1st time the following error is received: 

```
~/meshblu-johnny-five-rpi $ node index.js
ready event { api: 'connect',
  status: 201,
  socketid: 'SOCKET_ID',
  uuid: MESHBLU_UUID_HERE,
  token: 'MESHBLU_TOKEN_HERE' }
modprobe: ERROR: could not insert 'i2c_dev': Operation not permitted
child_process.js:1389
    throw err;
          ^
Error: Command failed: modprobe i2c-dev
modprobe: ERROR: could not insert 'i2c_dev': Operation not permitted
```

Executed:

```
sudo modprobe i2c-dev
```

then

```
node index.js
```

The following is received:

```
ready event { api: 'connect',
  status: 201,
  socketid: 'SOCKET_ID',
  uuid: 'MESHBLU_UUID,
  token: 'MESHBLU_TOKEN' }
wiringPiSetup: Must be root. (Did you forget sudo?)
```

**Comment by moodybass** [comment]
Update:
Performed fresh install of Raspberry Pi (Jessie).
Installed Node (0.12.6)
Installed NPM (3.3.12)
Upgraded GCC components to v4.8

On running node index.js in ~/meshblu-johnny-five-pi the following error occurs:

```
node index.js
ready event { api: 'connect',
status: 201, 
socketid: 'SOCKET_ID',
uuid: 'UUID',
token: 'TOKEN'}
wiringPiSetup: Must be root. (Did you forget sudo?)
Aborted
```

(Socket, UUID, Token edited).

**Comment by moodybass** [comment]
- incorrect -

**Comment by moodybass** [comment]
you need to run as sudo ;-)  WiringPi documentation confirms.  

Go use: https://github.com/octoblu/dynamic-j5 instead - far better functionality.

**Comment by virgilvox** [comment]
wow you've been busy!

If you're willing to try something experimental, there is this I put up awhile ago - https://github.com/octoblu/dynamic-j5-rpi/blob/master/main.js
